### ISSUE TITLE
"--print-window-info" prints out an error

### ISSUE THREAD

**Issue by eti0** [xhsdf/pxdo#1]
![2017-06-10-15 01 26](https://user-images.githubusercontent.com/14180792/27002957-1908fd9a-4ddd-11e7-9653-ca5765c89650.png)

`~ » pxdo.py --print-window-info`
`Unexpected error: <class 'TypeError'>`
`~ » pxdo.py --print-monitor-info`

Any idea why it's not working? python-xlib is correctly installed.
Running on Arch, system is up to date.

**Comment by xhsdf** [comment]
Can you comment out the try-except (lines 22, 38 and 39) and post the output again?

**Comment by eti0** [comment]
Like [so](https://0x0.st/Ip5.png)?

If so then it output this:
![2017-06-10-15 39 01](https://user-images.githubusercontent.com/14180792/27003218-34cad288-4de2-11e7-9281-61039d18162e.png)

**Comment by xhsdf** [comment]
What output does https://pastebin.com/dh5yQeHd give you?

**Comment by eti0** [comment]
Here's what it outputs:
![2017-06-10-15 57 42](https://user-images.githubusercontent.com/14180792/27003374-e077a686-4de4-11e7-875f-c53a6ab5ee49.png)

I also admit not being familiar with python at all.

[Here's a pastebin if you want the raw text data.](https://0x0.st/IfK.txt)

**Comment by xhsdf** [comment]
> also admit not being familiar with python at all. 

Me neither, but my only other option for this program was C...

Seems like some window has a weird wm_class. Does https://pastebin.com/nDz445xa fix the issue?

**Comment by eti0** [comment]
Yay!

![2017-06-10-16 10 13](https://user-images.githubusercontent.com/14180792/27003465-8ad46532-4de6-11e7-9e05-8c3d355da134.png)

Thanks for the fix :)

**Comment by xhsdf** [comment]
No problem!
