### ISSUE TITLE
Unexpected error: <class 'AttributeError'>

### ISSUE THREAD

**Issue by grvlle** [xhsdf/pxdo#3]
Got a problem when running:
vito@archlabs ~/.config % pxdo.py --print-window-info

It outputs: Unexpected error: <class 'AttributeError'>

Tried the previous fixes but none worked for my case. Thanks for an awesome project!

**Comment by xhsdf** [comment]
Hey there! Could you remove (or comment out) the following lines and post the output again?
23 (try:)
39 (except:)
40 (print("Unexpected error:", exc_info()[0]))

**Comment by grvlle** [comment]
Hi xhsdf,

Thanks for the quick reply. Here's the output requested:
```
vito@archlabs ~ % pxdo.py --print-window-info 
Traceback (most recent call last):
  File "/usr/bin/pxdo.py", line 219, in <module>
    main(argv[1:])
  File "/usr/bin/pxdo.py", line 31, in main
    print_window_info()
  File "/usr/bin/pxdo.py", line 49, in print_window_info
    for w in Window.get_windows():
  File "/usr/bin/pxdo.py", line 134, in get_windows
    w = Window.from_id(int(id))
  File "/usr/bin/pxdo.py", line 146, in from_id
    return Window(display.create_resource_object('window', wid), wid, full)
  File "/usr/bin/pxdo.py", line 110, in __init__
    self.name = self.get_property('WM_NAME').decode("ascii", errors='ignore').replace("\t", "  ")
AttributeError: 'NoneType' object has no attribute 'decode'
```

/grvlle

**Comment by xhsdf** [comment]
Seems like one of your windows has no name. Can you try if https://pastebin.com/raw/n8dsLPAs fixes the problem?

**Comment by grvlle** [comment]
That works! Awesome - thank you!

**Comment by xhsdf** [comment]
No problem! I commited the changes to the project. It should work now
